title: /Home
description: My Personal Stack Problems
author: Jeremy Palmer
github: https://github.com/xenenon
about: I'm a cybersecurity student. 
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-mastodon
      link: "https://infosec.exchange/@xenenon"
    - icon: fa-linkedin
      link: "https://linkedin.com/in/jeremyadampalmer"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/xenenon"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://xenenon.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
